version: "3"

services:
    api:
        build: .
        volumes:
          - dados_temp:/usr/src/app/temp/
        depends_on:
          - db
    db:
        image: postgres:12.0-alpine
        ports:
            - "6432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=chomikuj


volumes:
  postgres_data:
  dados_temp: